name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, zip
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: zip

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
