name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: zip

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
